{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a4c49e4e",
   "metadata": {},
   "source": [
    "## 0) 不要省略异常信息的记录\n",
    "\n",
    "很多时候，由于疏忽大意，开发者很容易捕获了异常却没有记录异常信息，导致程序上线后真的出现了问题却没有记录可查。\n",
    "\n",
    "```java\n",
    "public void logAnException() {\n",
    "    try {\n",
    "    } catch (NumberFormatException e) {\n",
    "        log.error(\"哦，错误竟然发生了: \" + e);\n",
    "    }\n",
    "}\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "70bc4f85",
   "metadata": {},
   "source": [
    "## 1) 尽量不要捕获 RuntimeException\n",
    "\n",
    "> 尽量不要 catch RuntimeException，比如 NullPointerException、IndexOutOfBoundsException 等等，应该用预检查的方式来规避。\n",
    "\n",
    "如果有些异常预检查不出来, 比如NumberFormatException也属于 RuntimeException，但没办法预检查，所以就应该用 catch 捕获处理.\n",
    "\n",
    "## 2) 尽量使用 try-with-resource 来关闭资源\n",
    "\n",
    "当需要关闭资源时，尽量不要使用 try-catch-finally，禁止在 try 块中直接关闭资源.\n",
    "\n",
    "```java\n",
    "// 反例\n",
    "public void doNotCloseResourceInTry() {\n",
    "    FileInputStream inputStream = null;\n",
    "    try {\n",
    "        File file = new File(\"./tmp.txt\");\n",
    "        inputStream = new FileInputStream(file);\n",
    "        inputStream.close();\n",
    "    } catch (FileNotFoundException e) {\n",
    "        log.error(e);\n",
    "    } catch (IOException e) {\n",
    "        log.error(e);\n",
    "    }\n",
    "}\n",
    "```\n",
    "\n",
    "原因也很简单，因为一旦 `close()` 之前发生了异常，那么资源就无法关闭。直接使用 **try-with-resource**来处理是最佳方式. \n",
    "\n",
    "```java\n",
    "public void automaticallyCloseResource() {\n",
    "    File file = new File(\"./tmp.txt\");\n",
    "    try (FileInputStream inputStream = new FileInputStream(file); {\n",
    "    } catch (FileNotFoundException e) {\n",
    "        log.error(e);\n",
    "    } catch (IOException e) {\n",
    "        log.error(e);\n",
    "    }\n",
    "}\n",
    "```\n",
    "\n",
    "如果资源没有实现 AutoCloseable 接口, 就在 finally 块关闭流:\n",
    "\n",
    "```java\n",
    "public void closeResourceInFinally() {\n",
    "    FileInputStream inputStream = null;\n",
    "    try {\n",
    "        File file = new File(\"./tmp.txt\");\n",
    "        inputStream = new FileInputStream(file);\n",
    "    } catch (FileNotFoundException e) {\n",
    "        log.error(e);\n",
    "    } finally {\n",
    "        if (inputStream != null) {\n",
    "            try {\n",
    "                inputStream.close();\n",
    "            } catch (IOException e) {\n",
    "                log.error(e);\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "}\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ad76b108",
   "metadata": {},
   "source": [
    "## 3) 不要在 finally 块中使用 return\n",
    "\n",
    "> try 块中的 return 语句执行成功后，并不会马上返回，而是继续执行 finally 块中的语句，如果 finally 块中也存在 return 语句，那么 try 块中的 return 就将被覆盖。\n",
    "\n",
    "```java\n",
    "private int x = 0;\n",
    "public int checkReturn() {\n",
    "    try {\n",
    "        return ++x;\n",
    "    } finally {\n",
    "        return ++x;\n",
    "    }\n",
    "}\n",
    "```\n",
    "\n",
    "## 4) 捕获具体的子类而不是捕获 Exception 类\n",
    "\n",
    "```java\n",
    "// 反例\n",
    "try {\n",
    "   someMethod();\n",
    "} catch (Exception e) {\n",
    "   LOGGER.error(\"method has failed\", e);\n",
    "}\n",
    "```\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4b731e14",
   "metadata": {},
   "source": [
    "## 5) finally 块中永远不要抛出任何异常\n",
    "\n",
    "```java\n",
    "try {\n",
    "  someMethod();  //Throws IndexException\n",
    "} finally {\n",
    "  cleanUp();    //如果finally还抛出异常，那么IndexException将永远丢失\n",
    "}\n",
    "```\n",
    "\n",
    "只要 `cleanUp()` 永远不会抛出任何异常，上面的代码没有问题，但是如果 `someMethod()` 抛出一个异常，并且在 finally 块中，`cleanUp()` 也抛出另一个异常，那么程序只会把第二个异常抛出来，原来的第一个异常（正确的原因）将永远丢失。如果在 finally 块中调用的代码可能会引发异常，请确保要么处理它，要么将其记录下来。永远不要让它从 finally 块中抛出来。\n",
    "\n",
    "## 6) 对于不打算处理的异常，直接使用 finally\n",
    "\n",
    "```java\n",
    "try {\n",
    "  someMethod();  //Method 2\n",
    "} finally {\n",
    "  cleanUp();    //do cleanup here\n",
    "}\n",
    "```\n",
    "\n",
    "这是一个很好的做法，如果在你的方法中你正在访问 Method 2，而 Method 2 抛出一些你不想在 Method 1 中处理的异常，但是仍然希望在发生异常时进行一些清理，然后在 finally 块中进行清理，不要使用 catch 块。\n",
    "\n",
    "## 7) 记住早 throw 晚 catch 原则\n",
    "\n",
    "\n",
    "这可能是关于异常处理最著名的原则，简单说，应该尽快抛出(throw)异常，并尽可能晚地捕获(catch)它。应该等到有足够的信息来妥善处理它。\n",
    "\n",
    "这个原则隐含地说，你将更有可能把它放在低级方法中，在那里你将检查单个值是否为空或不适合。而且你会让异常堆栈跟踪上升好几个级别，直到达到足够的抽象级别才能处理问题。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ed3f029",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
